### ISSUE TITLE
Add real tests and make it work in all the supported OSs

### ISSUE THREAD

**Issue by micafer** [grycap/ansible-role-blcr#1]

**Comment by amcaar** [comment]
No real tests with travis can be added to this role, due to the kernel version of the travis machines where the tests run (Linux kernel 4.4.0-51-generic build). The last version of BLCR is 0.8.5, which supports kernels through 3.7.1. See [BLCR Admin's Guide](https://upc-bugs.lbl.gov/blcr/doc/html/BLCR_Admin_Guide.html) for more information.
